// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package database

import (
	"context"
	"database/sql"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (width, height, file_size, format, path, data_url, preview_url, project_id )
VALUES (?,?,?,?,?,?,?,?)
RETURNING id, width, height, file_size, format, path, data_url, preview_url, project_id
`

type CreateImageParams struct {
	Width      sql.NullInt64
	Height     sql.NullInt64
	FileSize   sql.NullInt64
	Format     sql.NullString
	Path       string
	DataUrl    sql.NullString
	PreviewUrl sql.NullString
	ProjectID  int64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.Width,
		arg.Height,
		arg.FileSize,
		arg.Format,
		arg.Path,
		arg.DataUrl,
		arg.PreviewUrl,
		arg.ProjectID,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.Format,
		&i.Path,
		&i.DataUrl,
		&i.PreviewUrl,
		&i.ProjectID,
	)
	return i, err
}
