// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Image struct {
	ID         int64
	Width      sql.NullInt64
	Height     sql.NullInt64
	FileSize   sql.NullInt64
	Format     sql.NullString
	Path       string
	DataUrl    sql.NullString
	PreviewUrl sql.NullString
	ProjectID  int64
}

type Project struct {
	ID        int64
	Name      string
	Directory string
}
