// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, directory)
VALUES (?, ?)
RETURNING id, name, directory
`

type CreateProjectParams struct {
	Name      string
	Directory string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Directory)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.Directory)
	return i, err
}
