// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, directory)
VALUES (?, ?)
RETURNING id, name, directory
`

type CreateProjectParams struct {
	Name      string
	Directory string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.Directory)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.Directory)
	return i, err
}

const retrieveProjects = `-- name: RetrieveProjects :many
SELECT id, name, directory,(
        SELECT COUNT(*)
        FROM images
        WHERE images.project_id = projects.id
    ) AS image_count
FROM projects
`

type RetrieveProjectsRow struct {
	ID         int64
	Name       string
	Directory  string
	ImageCount int64
}

func (q *Queries) RetrieveProjects(ctx context.Context) ([]RetrieveProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, retrieveProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveProjectsRow
	for rows.Next() {
		var i RetrieveProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Directory,
			&i.ImageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
