// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package database

import (
	"context"
	"database/sql"
)

const createInspectionReport = `-- name: CreateInspectionReport :one
INSERT INTO inspection_reports (project_id, report_number)
VALUES (?, ?)
RETURNING id, project_id, report_number, report_title, customer_name, property_address, city_state_zip, inspector_name, inspection_date, insurance_carrier, claim_number, date_of_loss, summary, notes, created_at, updated_at, last_generated_pdf_path, last_generated_at, property_city, property_state, property_zip
`

type CreateInspectionReportParams struct {
	ProjectID    int64
	ReportNumber string
}

func (q *Queries) CreateInspectionReport(ctx context.Context, arg CreateInspectionReportParams) (InspectionReport, error) {
	row := q.db.QueryRowContext(ctx, createInspectionReport, arg.ProjectID, arg.ReportNumber)
	var i InspectionReport
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReportNumber,
		&i.ReportTitle,
		&i.CustomerName,
		&i.PropertyAddress,
		&i.CityStateZip,
		&i.InspectorName,
		&i.InspectionDate,
		&i.InsuranceCarrier,
		&i.ClaimNumber,
		&i.DateOfLoss,
		&i.Summary,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastGeneratedPdfPath,
		&i.LastGeneratedAt,
		&i.PropertyCity,
		&i.PropertyState,
		&i.PropertyZip,
	)
	return i, err
}

const getInspectionReport = `-- name: GetInspectionReport :one
SELECT id, project_id, report_number, report_title, customer_name, property_address, city_state_zip, inspector_name, inspection_date, insurance_carrier, claim_number, date_of_loss, summary, notes, created_at, updated_at, last_generated_pdf_path, last_generated_at, property_city, property_state, property_zip
FROM inspection_reports
WHERE id = ?
`

func (q *Queries) GetInspectionReport(ctx context.Context, id int64) (InspectionReport, error) {
	row := q.db.QueryRowContext(ctx, getInspectionReport, id)
	var i InspectionReport
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReportNumber,
		&i.ReportTitle,
		&i.CustomerName,
		&i.PropertyAddress,
		&i.CityStateZip,
		&i.InspectorName,
		&i.InspectionDate,
		&i.InsuranceCarrier,
		&i.ClaimNumber,
		&i.DateOfLoss,
		&i.Summary,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastGeneratedPdfPath,
		&i.LastGeneratedAt,
		&i.PropertyCity,
		&i.PropertyState,
		&i.PropertyZip,
	)
	return i, err
}

const getInspectionReportByProjectID = `-- name: GetInspectionReportByProjectID :one
SELECT id, project_id, report_number, report_title, customer_name, property_address, city_state_zip, inspector_name, inspection_date, insurance_carrier, claim_number, date_of_loss, summary, notes, created_at, updated_at, last_generated_pdf_path, last_generated_at, property_city, property_state, property_zip
FROM inspection_reports
WHERE project_id = ?
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetInspectionReportByProjectID(ctx context.Context, projectID int64) (InspectionReport, error) {
	row := q.db.QueryRowContext(ctx, getInspectionReportByProjectID, projectID)
	var i InspectionReport
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReportNumber,
		&i.ReportTitle,
		&i.CustomerName,
		&i.PropertyAddress,
		&i.CityStateZip,
		&i.InspectorName,
		&i.InspectionDate,
		&i.InsuranceCarrier,
		&i.ClaimNumber,
		&i.DateOfLoss,
		&i.Summary,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastGeneratedPdfPath,
		&i.LastGeneratedAt,
		&i.PropertyCity,
		&i.PropertyState,
		&i.PropertyZip,
	)
	return i, err
}

const retrieveReviewedReportImages = `-- name: RetrieveReviewedReportImages :many
SELECT
    images.id AS image_id,
    images.path AS image_path,
    ai_images.edited_annotations_json
FROM images
JOIN ai_images
    ON ai_images.image_id = images.id
WHERE images.project_id = (
    SELECT project_id
    FROM inspection_reports
    WHERE inspection_reports.id = ?
)
AND ai_images.edited_annotations_json IS NOT NULL
AND ai_images.edited_annotations_json <> ''
AND ai_images.review_approved = 1
ORDER BY images.id
`

type RetrieveReviewedReportImagesRow struct {
	ImageID               int64
	ImagePath             string
	EditedAnnotationsJson sql.NullString
}

func (q *Queries) RetrieveReviewedReportImages(ctx context.Context, id int64) ([]RetrieveReviewedReportImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, retrieveReviewedReportImages, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrieveReviewedReportImagesRow
	for rows.Next() {
		var i RetrieveReviewedReportImagesRow
		if err := rows.Scan(&i.ImageID, &i.ImagePath, &i.EditedAnnotationsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInspectionReport = `-- name: UpdateInspectionReport :one
UPDATE inspection_reports
SET
    report_number = ?,
    report_title = ?,
    customer_name = ?,
    property_address = ?,
    property_city = ?,
    property_state = ?,
    property_zip = ?,
    inspector_name = ?,
    inspection_date = ?,
    insurance_carrier = ?,
    claim_number = ?,
    date_of_loss = ?,
    summary = ?,
    notes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, project_id, report_number, report_title, customer_name, property_address, city_state_zip, inspector_name, inspection_date, insurance_carrier, claim_number, date_of_loss, summary, notes, created_at, updated_at, last_generated_pdf_path, last_generated_at, property_city, property_state, property_zip
`

type UpdateInspectionReportParams struct {
	ReportNumber     string
	ReportTitle      string
	CustomerName     string
	PropertyAddress  string
	PropertyCity     string
	PropertyState    string
	PropertyZip      string
	InspectorName    string
	InspectionDate   string
	InsuranceCarrier string
	ClaimNumber      string
	DateOfLoss       string
	Summary          string
	Notes            string
	ID               int64
}

func (q *Queries) UpdateInspectionReport(ctx context.Context, arg UpdateInspectionReportParams) (InspectionReport, error) {
	row := q.db.QueryRowContext(ctx, updateInspectionReport,
		arg.ReportNumber,
		arg.ReportTitle,
		arg.CustomerName,
		arg.PropertyAddress,
		arg.PropertyCity,
		arg.PropertyState,
		arg.PropertyZip,
		arg.InspectorName,
		arg.InspectionDate,
		arg.InsuranceCarrier,
		arg.ClaimNumber,
		arg.DateOfLoss,
		arg.Summary,
		arg.Notes,
		arg.ID,
	)
	var i InspectionReport
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReportNumber,
		&i.ReportTitle,
		&i.CustomerName,
		&i.PropertyAddress,
		&i.CityStateZip,
		&i.InspectorName,
		&i.InspectionDate,
		&i.InsuranceCarrier,
		&i.ClaimNumber,
		&i.DateOfLoss,
		&i.Summary,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastGeneratedPdfPath,
		&i.LastGeneratedAt,
		&i.PropertyCity,
		&i.PropertyState,
		&i.PropertyZip,
	)
	return i, err
}

const updateInspectionReportOutput = `-- name: UpdateInspectionReportOutput :exec
UPDATE inspection_reports
SET
    last_generated_pdf_path = ?,
    last_generated_at = ?
WHERE id = ?
`

type UpdateInspectionReportOutputParams struct {
	LastGeneratedPdfPath string
	LastGeneratedAt      string
	ID                   int64
}

func (q *Queries) UpdateInspectionReportOutput(ctx context.Context, arg UpdateInspectionReportOutputParams) error {
	_, err := q.db.ExecContext(ctx, updateInspectionReportOutput, arg.LastGeneratedPdfPath, arg.LastGeneratedAt, arg.ID)
	return err
}
