// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeImage(arg1) {
  return window['go']['main']['App']['AnalyzeImage'](arg1);
}

export function AnalyzeProject(arg1) {
  return window['go']['main']['App']['AnalyzeProject'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function GetOriginalImageDataURL(arg1) {
  return window['go']['main']['App']['GetOriginalImageDataURL'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RetrieveAiImages(arg1) {
  return window['go']['main']['App']['RetrieveAiImages'](arg1);
}

export function RetrieveProject(arg1) {
  return window['go']['main']['App']['RetrieveProject'](arg1);
}
