// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {analysis} from '../models';

export function AnalyzeImage(arg1:database.RetrieveImagesRow):Promise<analysis.AnalysisResult>;

export function AnalyzeProject(arg1:database.Project):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<database.Project>;

export function GetProjects():Promise<Array<database.RetrieveProjectsRow>>;

export function Greet(arg1:string):Promise<string>;

export function PickDirectory():Promise<string>;

export function RetrieveAiImages(arg1:number):Promise<Array<database.RetrieveAiImagesRow>>;

export function RetrieveProject(arg1:number):Promise<Array<database.RetrieveImagesRow>>;
