// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateProject(arg1:string,arg2:string):Promise<database.Project>;

export function Greet(arg1:string):Promise<string>;

export function PickDirectory():Promise<string>;

export function RetrieveProject(arg1:number):Promise<Array<database.RetrieveImagesRow>>;
