// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {analysis} from '../models';
import {inspection_reports} from '../models';

export function AnalyzeImage(arg1:database.RetrieveImagesRow):Promise<analysis.AnalysisResult>;

export function AnalyzeProject(arg1:database.Project):Promise<void>;

export function ApproveImageReview(arg1:number,arg2:string):Promise<void>;

export function CreateInspectionReport(arg1:number,arg2:string):Promise<database.InspectionReport>;

export function CreateProject(arg1:string,arg2:string):Promise<database.Project>;

export function DeleteProject(arg1:number):Promise<void>;

export function GenerateInspectionReport(arg1:number,arg2:string):Promise<inspection_reports.Result>;

export function GetInspectionReportByProjectID(arg1:number):Promise<database.InspectionReport>;

export function GetOriginalImageDataURL(arg1:number):Promise<string>;

export function GetProjects():Promise<Array<database.RetrieveProjectsRow>>;

export function Greet(arg1:string):Promise<string>;

export function OpenLastGeneratedInspectionReport(arg1:number):Promise<void>;

export function PickDirectory():Promise<string>;

export function RetrieveAiImages(arg1:number):Promise<Array<database.RetrieveAiImagesRow>>;

export function RetrieveProject(arg1:number):Promise<Array<database.RetrieveImagesRow>>;

export function SaveEditedAnnotations(arg1:number,arg2:string):Promise<void>;

export function UpdateInspectionReport(arg1:database.UpdateInspectionReportParams):Promise<database.InspectionReport>;
